--2. Выполнить SELECT-запрос из п. 1 с использованием CUBE-группировки. 
--Проанализировать результат.

SELECT 
  F.FACULTY, 
  PF.PROFESSION_NAME, 
  P.SUBJECT, 
  AVG(P.NOTE) AS AVG_GRADE 
FROM 
  FACULTY F
  JOIN GROUPS G on G.FACULTY = F.FACULTY
  JOIN STUDENT S on S.IDGROUP = G.IDGROUP
  JOIN PROGRESS P on P.IDSTUDENT = S.IDSTUDENT
  JOIN PROFESSION PF on PF.PROFESSION = G.PROFESSION 
WHERE 
  F.FACULTY = 'ИДиП' 
GROUP BY
CUBE(
  F.FACULTY, 
  PF.PROFESSION_NAME, 
  P.SUBJECT )